sudo: false
language: ruby
before_install:
  - gem install bundler -v '< 2'
bundler_args: --without development
rvm:
  - 2.1
script: bundle exec rake spec SPEC_OPTS='--color --format documentation'
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.5.1"
    - PUPPET_GEM_VERSION="~> 3.7.1"
    - PUPPET_GEM_VERSION="~> 3.8.6"
